#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qgit
Version  : 2.10
Release  : 4
URL      : https://github.com/tibirna/qgit/archive/qgit-2.10/qgit-2.10.tar.gz
Source0  : https://github.com/tibirna/qgit/archive/qgit-2.10/qgit-2.10.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: qgit-bin = %{version}-%{release}
Requires: qgit-data = %{version}-%{release}
Requires: qgit-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : qtbase-dev mesa-dev

%description
This is qgit.exe statically linked to Trolltech Qt4.3.3 for Windows Open source edition

%package bin
Summary: bin components for the qgit package.
Group: Binaries
Requires: qgit-data = %{version}-%{release}
Requires: qgit-license = %{version}-%{release}

%description bin
bin components for the qgit package.


%package data
Summary: data components for the qgit package.
Group: Data

%description data
data components for the qgit package.


%package license
Summary: license components for the qgit package.
Group: Default

%description license
license components for the qgit package.


%prep
%setup -q -n qgit-qgit-2.10
cd %{_builddir}/qgit-qgit-2.10

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1641856639
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1641856639
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qgit
cp %{_builddir}/qgit-qgit-2.10/COPYING.rtf %{buildroot}/usr/share/package-licenses/qgit/2799e74aec7d7b12baa3507b0875fcc2c780ebd7
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qgit

%files data
%defattr(-,root,root,-)
/usr/share/applications/qgit.desktop
/usr/share/icons/hicolor/48x48/apps/qgit.png
/usr/share/icons/hicolor/scalable/apps/qgit.svg
/usr/share/metainfo/qgit.appdata.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qgit/2799e74aec7d7b12baa3507b0875fcc2c780ebd7
