#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : qgit
Version  : 2.8
Release  : 1
URL      : https://github.com/tibirna/qgit/archive/qgit-2.8.tar.gz
Source0  : https://github.com/tibirna/qgit/archive/qgit-2.8.tar.gz
Summary  : A GIT GUI viewer built on Qt/C++
Group    : Development/Tools
License  : GPL-2.0
Requires: qgit-bin = %{version}-%{release}
Requires: qgit-data = %{version}-%{release}
Requires: qgit-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-qmake
BuildRequires : qtbase-dev mesa-dev

%description
qgit, a git GUI viewer
======================
With qgit you will be able to browse revisions history, view patch content
and changed files, graphically following different development branches.

%package bin
Summary: bin components for the qgit package.
Group: Binaries
Requires: qgit-data = %{version}-%{release}
Requires: qgit-license = %{version}-%{release}

%description bin
bin components for the qgit package.


%package data
Summary: data components for the qgit package.
Group: Data

%description data
data components for the qgit package.


%package license
Summary: license components for the qgit package.
Group: Default

%description license
license components for the qgit package.


%prep
%setup -q -n qgit-qgit-2.8

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1548339462
mkdir -p clr-build
pushd clr-build
%cmake ..
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1548339462
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/qgit
cp COPYING.rtf %{buildroot}/usr/share/package-licenses/qgit/COPYING.rtf
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/qgit

%files data
%defattr(-,root,root,-)
/usr/share/applications/qgit.desktop
/usr/share/icons/hicolor/48x48/apps/qgit.png
/usr/share/metainfo/qgit.appdata.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/qgit/COPYING.rtf
